In [9]:
# 7-Numpy_Pandas
#Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. 

import numpy as np
array1=np.arange(1,11).reshape(2,5)
print("Exercise 1:")
print(array1)


Exercise 1:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:

#Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 

print("Exercise 2:")
array2=np.arange(1,21)
print(array2)
res_array2=array2[5:16]
print(res_array2)

Exercise 2:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [31]:

#Exercise 3: (Score : 2) Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. 
#Then, add a new item to the series with the key 'pears' and the value 4. 

import pandas as pd
array3={'apples': 3, 'bananas': 2, 'oranges': 1}
p_array1=pd.Series(array3)
p_array1['pears']=4
p_array1

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

In [37]:

#Exercise 4: (Score : 2) Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

d_frame1=pd.DataFrame({
    'name':['Sachin','Ellyse Perry','Ponting','Sangakkara','Kallis','Amla','Jayawardane','Brian Lara','Smriti Mandhana','Meg Lanning'],
    'Age':[51,34,50,47,49,41,47,55,29,33],
    'Gender':['M','F','M','M','M','M','M','M','F','F']})
print(d_frame1)

              name  Age Gender
0           Sachin   51      M
1     Ellyse Perry   34      F
2          Ponting   50      M
3       Sangakkara   47      M
4           Kallis   49      M
5             Amla   41      M
6      Jayawardane   47      M
7       Brian Lara   55      M
8  Smriti Mandhana   29      F
9      Meg Lanning   33      F


In [39]:

#Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. 

occupation=['Manager','Analyst','Manager','Manager','Analyst','Programmer','Manager','Manager','Programmer','Programmer']
d_frame1['Occupation']=occupation
print(d_frame1)

              name  Age Gender  Occupation
0           Sachin   51      M     Manager
1     Ellyse Perry   34      F     Analyst
2          Ponting   50      M     Manager
3       Sangakkara   47      M     Manager
4           Kallis   49      M     Analyst
5             Amla   41      M  Programmer
6      Jayawardane   47      M     Manager
7       Brian Lara   55      M     Manager
8  Smriti Mandhana   29      F  Programmer
9      Meg Lanning   33      F  Programmer


In [51]:

#Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30. 
d_frame_age_30pl=d_frame1[d_frame1['Age']>=30]
print(d_frame_age_30pl)


           name  Age Gender  Occupation
0        Sachin   51      M     Manager
1  Ellyse Perry   34      F     Analyst
2       Ponting   50      M     Manager
3    Sangakkara   47      M     Manager
4        Kallis   49      M     Analyst
5          Amla   41      M  Programmer
6   Jayawardane   47      M     Manager
7    Brian Lara   55      M     Manager
9   Meg Lanning   33      F  Programmer


In [55]:

#Exercise 7: (Score : 2) Convert this dataframe to a csv file and read that csv file, finally display the contents.

d_frame.to_csv('dframe1.csv',index=false)
new_dframe1=pd.read_csv('output.csv')
print(new_dframe1)

NameError: name 'd_frame' is not defined